# Generated by Django 4.1 on 2023-12-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'permissions': [('can_view_other_persons', 'Can view other persons')], 'verbose_name_plural': 'Osoby'},
        ),
    ]
